import { AlertOctagon, BadgeDollarSign, Gift, KeyRound, Link2, QrCode, Siren, UserRoundCheck, Wrench } from 'lucide-react'

const topics = [
  { icon: Siren, title: 'Urgency', meaning: 'Language that pressures you to act before you can verify.', example: '“Educational example: respond within 30 minutes to prevent closure.”', risk: 'Pressure can reduce careful thinking and independent checking.', verify: 'Pause and check the request in the official app or website.' },
  { icon: UserRoundCheck, title: 'Impersonation', meaning: 'A sender presents themselves as a trusted organization or person.', example: '“Educational example: I am calling from your bank support desk.”', risk: 'Names and logos are easy to copy in messages and pages.', verify: 'Contact the organization using a number you found independently.' },
  { icon: KeyRound, title: 'Credential Requests', meaning: 'Requests for passwords, OTPs, PINs, CVVs, or account verification.', example: '“Educational example: share the OTP to complete verification.”', risk: 'Authentication secrets can allow account access or transaction approval.', verify: 'Legitimate support staff should not need your password or OTP.' },
  { icon: Link2, title: 'Suspicious Links', meaning: 'Links whose real registered domain is hidden or difficult to read.', example: '“Educational example: bank-login.example.com is controlled by example.com.”', risk: 'Trusted words can appear before an unrelated registered domain.', verify: 'Read the hostname from right to left and use a known bookmark.' },
  { icon: BadgeDollarSign, title: 'Unexpected Payments', meaning: 'Unsolicited requests for a fee, fine, refund charge, or urgent transfer.', example: '“Educational example: pay a small delivery fee to release a parcel.”', risk: 'Small payments can expose card data and lead to further demands.', verify: 'Check the order or bill in the provider’s official service.' },
  { icon: Gift, title: 'Fake Rewards', meaning: 'Unexpected prize, lottery, cashback, or gift claims.', example: '“Educational example: you won a reward; pay processing to claim it.”', risk: 'The reward can be bait for personal data or advance fees.', verify: 'Confirm whether you entered a promotion and inspect its official rules.' },
  { icon: QrCode, title: 'QR Phishing', meaning: 'A QR image hides text or a URL until it is scanned.', example: '“Educational example: scan to resolve an account alert.”', risk: 'The destination is harder to inspect before scanning.', verify: 'Preview decoded content and verify the domain before opening it.' },
  { icon: Wrench, title: 'Tech Support Scams', meaning: 'Unexpected claims that your device needs repair or remote access.', example: '“Educational example: install this app so support can fix your phone.”', risk: 'Remote-access tools can expose screens, files, and financial activity.', verify: 'End the conversation and contact official support independently.' }
]

export default function LearnPage() {
  return <main><section className="border-b border-stone-200 bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><span className="inline-flex items-center gap-2 rounded-full bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800"><AlertOctagon size={14}/>Fictional examples only</span><h1 className="mt-6 text-4xl font-black tracking-tight text-[#28233e] sm:text-6xl">Scam Signal Library</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-stone-600">Learn how common persuasion and phishing patterns work—without treating any single word as proof of a scam.</p></div></section><section className="py-20"><div className="mx-auto grid max-w-7xl gap-5 px-5 md:grid-cols-2 lg:px-8">{topics.map(({icon:Icon,title,meaning,example,risk,verify}) => <article key={title} className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-700"><Icon size={20}/></span><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{meaning}</p><blockquote className="mt-4 rounded-xl border-l-4 border-amber-400 bg-amber-50 p-3 text-xs italic leading-5 text-stone-700">{example}</blockquote><dl className="mt-5 grid gap-4 text-sm"><div><dt className="font-bold text-stone-800">Why it can be risky</dt><dd className="mt-1 leading-6 text-stone-500">{risk}</dd></div><div><dt className="font-bold text-indigo-800">What to verify</dt><dd className="mt-1 leading-6 text-stone-500">{verify}</dd></div></dl></article>)}</div></section></main>
}
