import { useState } from 'react'
import { Clock3, Eye, History, Trash2, X } from 'lucide-react'

const typeLabel = value => value === 'qr' ? 'QR Code' : value?.charAt(0).toUpperCase() + value?.slice(1)

export default function HistoryDrawer({ open, onClose, history, onDelete, onClear }) {
  const [viewing, setViewing] = useState(null)
  return <><button aria-label="Close history overlay" tabIndex={open ? 0 : -1} onClick={onClose} className={`fixed inset-0 z-40 bg-stone-950/30 backdrop-blur-sm transition ${open ? 'visible opacity-100' : 'invisible opacity-0'}`}/><aside role="dialog" aria-modal="true" aria-hidden={!open} inert={!open ? '' : undefined} aria-label="Analysis history" className={`fixed right-0 top-0 z-50 flex h-full w-full max-w-md flex-col border-l border-stone-200 bg-[#fbfaf7] shadow-2xl transition-transform ${open ? 'translate-x-0' : 'translate-x-full'}`}>
    <div className="flex items-center justify-between border-b border-stone-200 p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><History size={19}/></span><div><h2 className="font-bold">Recent checks</h2><p className="text-xs text-stone-500">Only minimal metadata is stored</p></div></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-stone-100" aria-label="Close"><X size={19}/></button></div>
    <div className="flex-1 space-y-3 overflow-y-auto p-5">{history.length ? history.map(item => <article key={item.id} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="mb-3 flex items-start justify-between gap-3"><div><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-indigo-700">{typeLabel(item.type)}</span><h3 className="mt-3 line-clamp-2 text-sm font-bold text-stone-800">{item.description}</h3><p className="mt-1 flex items-center gap-1 text-[11px] text-stone-400"><Clock3 size={11}/>{new Date(item.timestamp).toLocaleString()}</p></div><div className="text-right"><b className="text-2xl text-indigo-800">{item.score}</b><span className="text-xs text-stone-400">/100</span></div></div>{viewing === item.id && <dl className="mb-3 grid grid-cols-2 gap-2 rounded-xl bg-stone-50 p-3 text-xs"><div><dt className="text-stone-400">Analysis type</dt><dd className="mt-1 font-bold">{typeLabel(item.type)}</dd></div><div><dt className="text-stone-400">Assessment</dt><dd className="mt-1 font-bold">{item.label}</dd></div><div className="col-span-2"><dt className="text-stone-400">Stored description</dt><dd className="mt-1 break-all font-bold">{item.description}</dd></div></dl>}<div className="flex items-center justify-between border-t border-stone-100 pt-3"><button onClick={() => setViewing(viewing === item.id ? null : item.id)} className="flex items-center gap-1.5 text-xs font-semibold text-indigo-700"><Eye size={14}/>{viewing === item.id ? 'Hide' : 'View'}</button><button onClick={() => onDelete(item.id)} className="rounded-lg p-2 text-stone-400 hover:bg-red-50 hover:text-red-600" aria-label={`Delete ${item.description}`}><Trash2 size={15}/></button></div></article>) : <div className="py-20 text-center"><Eye className="mx-auto text-stone-300" size={36}/><p className="mt-3 font-semibold">No checks saved yet</p><p className="mt-1 text-sm text-stone-500">Full messages and QR images are never stored.</p></div>}</div>
    {history.length > 0 && <div className="border-t border-stone-200 p-5"><button onClick={onClear} className="w-full rounded-xl border border-red-200 py-3 text-sm font-bold text-red-700 hover:bg-red-50">Clear All</button></div>}
  </aside></>
}
