import { CheckCircle2, ChevronDown, Download, Fingerprint, Lightbulb, Link2, ListChecks } from 'lucide-react'

const styles = {
  low: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  some: 'bg-amber-50 text-amber-800 border-amber-200',
  suspicious: 'bg-orange-50 text-orange-800 border-orange-200',
  strong: 'bg-red-50 text-red-800 border-red-200'
}

function toneFor(score) { return score <= 24 ? 'low' : score <= 49 ? 'some' : score <= 74 ? 'suspicious' : 'strong' }

function Breakdown({ data }) {
  if (!data) return null
  const values = [['Protocol', data.protocol], ['Hostname', data.hostname], ['Subdomain', data.subdomain], ['Domain', data.domain], ['Port', data.port], ['Path', data.path]]
  return <section className="rounded-3xl border border-stone-200 bg-white p-5 sm:p-7"><div className="mb-5"><h3 className="text-xl font-bold">Link Breakdown</h3><p className="mt-1 text-sm text-stone-500">Readable URL anatomy—this destination was not opened.</p></div><dl className="grid overflow-hidden rounded-2xl border border-stone-200 sm:grid-cols-2">{values.map(([label,value]) => <div key={label} className="min-w-0 border-b border-stone-100 p-4 even:bg-stone-50/50 sm:[&:nth-last-child(-n+2)]:border-b-0"><dt className="text-[10px] font-bold uppercase tracking-wider text-stone-400">{label}</dt><dd className="mt-1 break-all font-mono text-xs text-stone-700">{value}</dd></div>)}<div className="p-4 sm:col-span-2"><dt className="text-[10px] font-bold uppercase tracking-wider text-stone-400">Query parameters · {data.queryParameters.length}</dt><dd className="mt-2 flex flex-wrap gap-2">{data.queryParameters.length ? data.queryParameters.map(({key,value}, index) => <code key={`${key}-${index}`} className="max-w-full break-all rounded-lg bg-indigo-50 px-2 py-1 text-xs text-indigo-800">{key}={value}</code>) : <span className="text-xs text-stone-500">None</span>}</dd></div></dl></section>
}

export default function ResultPanel({ result, onAnalyzeLink }) {
  if (!result) return null
  const tone = toneFor(result.score)
  const exportReport = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], {type: 'application/json'})
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${result.id.toLowerCase()}-linkguard-report.json`; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(link.href), 0)
  }
  return <section className="mt-8 scroll-mt-24" aria-live="polite">
    <div className="overflow-hidden rounded-[2rem] border border-stone-200 bg-[#28233e] text-white shadow-xl shadow-stone-900/10">
      <div className="grid gap-8 p-6 sm:p-9 lg:grid-cols-[220px_1fr] lg:items-center">
        <div className="flex items-center gap-5 lg:block lg:text-center"><div className="relative grid h-28 w-28 shrink-0 place-items-center rounded-full bg-white/10 ring-8 ring-white/5 lg:mx-auto"><span className="text-4xl font-black">{result.score}</span><span className="absolute bottom-5 text-[10px] text-white/50">/ 100</span></div><div className="lg:mt-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-violet-300">Risk Signal Score</p><p className="mt-2 font-bold">{result.label}</p></div></div>
        <div><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Assessment</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">{result.pattern || result.label}</h2></div><button onClick={exportReport} className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2 text-xs font-bold hover:bg-white/10"><Download size={14}/>Export JSON</button></div><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">{result.summaryText || result.summary}</p><div className="mt-5 flex flex-wrap gap-3 text-[11px] text-white/50"><span className="flex items-center gap-1.5"><Fingerprint size={13}/>Report {result.id}</span><span>{result.findings.length} explainable signal{result.findings.length === 1 ? '' : 's'}</span><span>Analyzed locally</span></div></div>
      </div>
    </div>

    {result.type === 'qr' && <section className="mt-5 rounded-3xl border border-stone-200 bg-white p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Decoded content · {result.contentType}</p><h3 className="mt-2 text-lg font-bold">What the QR code contains</h3></div><span className="rounded-full bg-stone-100 px-3 py-1 text-xs text-stone-500">{result.dimensions}</span></div><pre className="mt-4 whitespace-pre-wrap break-all rounded-2xl bg-stone-50 p-4 font-mono text-xs leading-6 text-stone-700">{result.content}</pre><p className="mt-3 text-xs text-stone-500">Displayed as inert text. LinkGuard did not open, call, email, or connect to this content.</p></section>}

    <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <section className="rounded-3xl border border-stone-200 bg-white p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Evidence</p><h3 className="mt-1 text-xl font-bold">Why was this flagged?</h3></div><span className={`rounded-full border px-3 py-1 text-xs font-bold ${styles[tone]}`}>{result.findings.length} found</span></div>{result.findings.length ? <div className="space-y-3">{result.findings.map((item, index) => <details key={item.key || item.id || index} className="group rounded-2xl border border-stone-200 bg-[#fbfaf7] p-4" open={index < 2}><summary className="flex cursor-pointer list-none items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${item.severity === 'High' ? 'bg-red-500' : item.severity === 'Medium' ? 'bg-amber-500' : 'bg-indigo-400'}`}/><b className="min-w-0 flex-1 text-sm">{item.title}</b><span className="text-[10px] font-bold uppercase text-stone-400">{item.severity} · +{item.weight}</span><ChevronDown className="transition group-open:rotate-180" size={15}/></summary><div className="mt-4 border-t border-stone-200 pt-4"><code className="block break-all rounded-lg bg-white p-3 text-xs leading-5 text-indigo-800">{item.evidence || item.detected}</code><p className="mt-3 text-sm leading-6 text-stone-600">{item.explanation || item.why}</p></div></details>)}</div> : <div className="rounded-2xl bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto text-emerald-600"/><b className="mt-3 block text-emerald-900">No configured signals detected</b><p className="mt-1 text-sm text-emerald-800/70">Absence of these signals is not proof of safety.</p></div>}</section>
      <div className="space-y-5">{result.pattern && <section className="rounded-3xl border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Possible Pattern</p><p className="mt-2 text-lg font-bold">{result.pattern}</p><p className="mt-2 text-xs leading-5 text-stone-500">A rule-based possibility, not a definitive scam classification.</p></section>}{result.possibleIntent?.length > 0 && <section className="rounded-3xl border border-stone-200 bg-white p-5"><h3 className="flex items-center gap-2 font-bold"><Lightbulb size={17} className="text-amber-600"/>Possible Intent</h3><ul className="mt-3 space-y-2">{result.possibleIntent.map(item => <li key={item} className="flex gap-2 text-sm leading-5 text-stone-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500"/>{item}</li>)}</ul></section>}<section className="rounded-3xl border border-stone-200 bg-[#fff9e8] p-5"><h3 className="flex items-center gap-2 font-bold"><ListChecks size={18} className="text-amber-700"/>What Should I Do?</h3><ul className="mt-4 space-y-3">{(result.recommendations || ['Verify the sender and destination using an independent, trusted channel.']).map(item => <li key={item} className="flex gap-2 text-sm leading-6 text-stone-700"><CheckCircle2 className="mt-1 shrink-0 text-amber-700" size={15}/>{item}</li>)}</ul></section></div>
    </div>
    {result.links?.length > 0 && <section className="mt-5 rounded-3xl border border-stone-200 bg-white p-5 sm:p-7"><h3 className="flex items-center gap-2 text-xl font-bold"><Link2 className="text-indigo-700"/>Links Found</h3><p className="mt-1 text-sm text-stone-500">Inspect an extracted link without navigating to it.</p><div className="mt-4 space-y-2">{result.links.map((link,index) => <div key={`${link}-${index}`} className="flex flex-col gap-3 rounded-2xl bg-stone-50 p-4 sm:flex-row sm:items-center"><code className="min-w-0 flex-1 break-all text-xs text-stone-700">{link}</code><button onClick={() => onAnalyzeLink(link)} className="shrink-0 rounded-full bg-indigo-700 px-4 py-2 text-xs font-bold text-white hover:bg-indigo-800">Analyze This Link</button></div>)}</div></section>}
    <div className="mt-5"><Breakdown data={result.breakdown || result.linkResult?.breakdown}/></div>
  </section>
}
